CREATE TABLE noteful_notes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  modified TIMESTAMP NOT NULL DEFAULT now(),
  content TEXT NOT NULL
);

ALTER TABLE noteful_notes
    ADD COLUMN folderId INTEGER REFERENCES noteful_folders
    on delete set NULL;